version: '3.1'

services:
  backend:
    build: .
    restart: always
    container_name: kaktus-api
    ports:
      - 8080:8080
  mongo:
    image: mongo:7
    restart: unless-stopped
    container_name: kaktus-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}