version: '3.1'

services:
  backend:
    image: cr.yandex/${CR_ID}/kaktus-api
    restart: unless-stopped
    container_name: kaktus-api
    ports:
      - 8080:8080
  nginx:
    image: nginx:stable
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
  mongo:
    image: mongo:7
    restart: unless-stopped
    container_name: kaktus-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
