name: Deploy
run-name: CD Proccess

on:
  push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Copy file to server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.VM_DEPLOY_IP }}
          username: ${{ secrets.VM_DEPLOY_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: whoami
