name: Deploy
run-name: CD Proccess

on:
  push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Publish to Yandex Container Registry
        env:
          CR_REGISTRY: ${{ secrets.YC_CI_REGISTRY }}
          CR_REPO: kaktus-api
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPO:latest .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPO:latest

      - name: Export ENV
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.VM_DEPLOY_IP }}
          username: ${{ secrets.VM_DEPLOY_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            export CR_ID=${{ secrets.YC_CI_REGISTRY }}

      - name: Copy docker-compose file
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VM_DEPLOY_IP }}
          username: ${{ secrets.VM_DEPLOY_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "./docker-compose.yml"
          target: /app
